component_depth: 1
languages:
        - name: java
          production:
                  exclude:
                          - .*/integrationTest/.*.java
          test:
                  include:
                          - .*/integrationTest/.*.java


