language: java
jdk:
  - oraclejdk8
script: ./gradlew check --info
sudo: false
cache:
  directories:
  - $HOME/.gradle

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
