language: java
jdk:
- oraclejdk8
script: "./ci.sh"
sudo: false
cache:
  directories:
  - "$HOME/.gradle"
after_success:
- bash <(curl -s https://codecov.io/bash)
after_script:
- bash update-gh-pages.sh
env:
  global:
    secure: XbdnUBVo2yoE0mlQaSllYYeQvrTgIv8iPy5xjzlhkGaR1G2YR3MQcioso/8FMRBqHKtyUjt8lUiqUDv0yUhwjN55kS2IADVpPtehyra4kkT2jCnkZBfzaMwX86Q8RUaauy/y99gV4j3KA2x5RjwV6TqHIPApsXAqCX+mPb1sglGIZKnOAc8DeQ6Sgs7EXemqbNWruMNQjtFOLvcsxqjqlacHQ+RhYmhJEtFVnwDWuaMK6pxkUoLRv08bL6r7jI6FYSVF/KiyDjrY8jiBZ/U0fk/Ptc4R+foP9IWXskW9EQk5Ms+gZH6TltYlT+R84yn6XKLG6MdlC+HfFOdh9Z/5l2NuB6AFxU4biSznD7eVb2XjGqi6cU/4R9Einzqewa64jXiMMrDy+v/nFGhuBiuDn3lu51gJvHryOyzTPEGxO+U8+ZdPe69Du0UC812mxzvChMtEIVG6CiYReYeZmcr+2seRWGzgNeBzf0Iz1vWrY6CNQD90Jw/PUuX0ox1Ps9JdNOp1LDiaYTzkG82BoPrNZiv6V1r4FOCJ0w8AQAL+GpeupxL8a0XBozGIzKuonYIR2ThgGM+qvsO4Rjz8FaXbV6bpVLRCTznQOEalyr184K1+ENUnMyjDARj4S4JUPiHqiiHotTo505OkgbfwE6WKEKjLhe5LK+dxg57U+Ogwnk0=
