#cloud-config

#apt_sources:
# - source: "ppa:webupd8team/java"
#
#repo_update: true
#repo_upgrade: all
#
#packages:
#  - git
#  - curl

runcmd:
#  - curl -L https://s3-eu-west-1.amazonaws.com/uva-vampires/create_keys | bash
#  - curl -L https://s3-eu-west-1.amazonaws.com/uva-vampires/install_docker | bash
#  - echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && apt-get install -y oracle-java8-installer ca-certificates
#  - docker pull busybox
  - sudo -u ubuntu sh -c 'cd /home/ubuntu && git clone git@bitbucket.com:cdumitru/vampires-akka.git  && cd vampires-akka && ./gradlew installLocal'
  - sudo -u ubuntu nohup sh -c '$command' 2>&1 > /dev/null

